apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sharebike-dev
  labels:
    name: microservice1-deployment
  name: microservice1-deployment
spec:
  replicas: NUMBER_OF_REPLICAS
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: microservice1-deployment
    spec:
      containers:
      - name: microservice1-deployment
        image: gcr.io/helical-study-261016/test:latest
        ports:
         - containerPort: 8080
        resources:
#https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 50
        readinessProbe:
          httpGet:
#            path: /readiness
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 50
      volumes:
        - name: cloudsql-secret
          emptyDir:
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: microservice1-service
  name: microservice1-service-public
  namespace: sharebike-dev
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    name: microservice1-deployment